# Generated by Django 5.1.6 on 2025-02-26 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_reviewcategoryrating'),
        ('api', '0005_rename_author_review_user'),
    ]

    operations = [
    ]
