# Generated by Django 5.1.6 on 2025-02-26 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20250226_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcategoryrating',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_category_ratings', to='api.review'),
        ),
    ]
