# Generated by Django 5.1.7 on 2025-04-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_review_anonymous_review_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('base', 'Base'), ('topping', 'Topping')], default='base', max_length=100),
        ),
    ]
