# Generated by Django 5.1.7 on 2025-04-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_restaurant_image_alter_category_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Base', 'base'), ('Topping', 'topping')], default='base', max_length=100),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
