# Generated by Django 5.1.7 on 2025-05-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20250518_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Base', 'base'), ('Topping', 'topping')], default='base', max_length=100),
        ),
    ]
