# Generated by Django 5.1.7 on 2025-05-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('base', 'Base'), ('Topping', 'topping')], default='base', max_length=100),
        ),
    ]
