# Generated by Django 5.1.7 on 2025-05-19 06:55

import backend.storages_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Base', 'base'), ('topping', 'Topping')], default='base', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=backend.storages_backend.RestaurantStorage(), upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='homecard',
            unique_together={('message', 'image')},
        ),
    ]
