# Generated by Django 5.1.7 on 2025-05-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_homecard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('base', 'Base'), ('topping', 'Topping')], default='base', max_length=100),
        ),
    ]
