# Generated by Django 5.1.7 on 2025-05-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_restaurant_image_restaurantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
